baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'SUDDEN DESU'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Entries'
pageRef = '/entry'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
